<script language="vb" runat="server">
Dim sUsername, sPassword
Dim aStyle()
Dim aToolbar()
</script>

<%
sUsername = "admin"
sPassword = "GSGL$2011_SITE"

Redim aStyle(11)
aStyle(1) = "gray|||standard|||office|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(2) = "full|||standard|||coolblue|||uploadfile/|||550|||400|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||酷蓝样式，全部功能按钮|||1|||zh-cn"
aStyle(3) = "light|||standard|||light|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格按钮+淡色，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(4) = "blue|||standard|||blue|||../uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||300|||500|||300|||300|||100|||1|||1|||EDIT|||1|||0|||2|||||||||1|||1|||Office标准风格按钮+蓝色，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(5) = "green|||standard|||green|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格按钮+绿色，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(6) = "red|||standard|||red|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格按钮+红色，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(7) = "yellow|||standard|||yellow|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格按钮+黄色，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(8) = "3d|||standard|||office3d|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||Office标准风格3D凹凸按钮，部分常用按钮，标准适合界面宽度|||1|||zh-cn"
aStyle(9) = "coolblue|||standard|||coolblue|||../../uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||2|||0|||2|||||||||1|||0|||COOL界面，蓝色主调，标准风格，部分常用按钮，标准适合界面宽度，默认样式|||1|||zh-cn"
aStyle(10) = "mini|||standard|||coolblue|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||mini全菜单风格，全部功能按钮，工具栏占位小，标准界面宽度|||1|||zh-cn"
aStyle(11) = "popup|||standard|||coolblue|||uploadfile/|||550|||350|||rar|zip|exe|doc|xls|chm|hlp|||swf|||gif|jpg|jpeg|bmp|||rm|mp3|wav|mid|midi|ra|avi|mpg|mpeg|asf|asx|wma|mov|||gif|jpg|jpeg|bmp|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0|||0|||||||||1|||0|||酷蓝样式，主要用于标准弹窗，增加弹窗返回按钮。|||1|||zh-cn"

Redim aToolbar(30)
aToolbar(1) = "1|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(2) = "1|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(3) = "1|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(4) = "2|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(5) = "2|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(6) = "2|||TBHandle|Image|Flash|Media|File|RemoteUpload|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|Code|||高级工具栏|||3"
aToolbar(7) = "2|||TBHandle|Paragraph|BR|TBSep|TableInsert|TableProp|TBSep|TableCellProp|TableCellSplit|TBSep|TableRowProp|TableRowInsertAbove|TableRowInsertBelow|TableRowMerge|TableRowSplit|TableRowDelete|TBSep|TableColInsertLeft|TableColInsertRight|TableColMerge|TableColSplit|TableColDelete|TBSep|FormText|FormTextArea|FormRadio|FormCheckbox|FormDropdown|FormButton|||表格与表单|||4"
aToolbar(8) = "2|||TBHandle|EditMenu|FontMenu|ParagraphMenu|ComponentMenu|ObjectMenu|ToolMenu|TableMenu|FormMenu|FileMenu|ZoomMenu|TBSep|Refresh|Save|TBSep|Print|TBSep|ModeCode|ModeEdit|ModeText|ModeView|TBSep|SizePlus|SizeMinus|TBSep|Maximize|TBSep|About|Site|||菜单与状态|||5"
aToolbar(9) = "3|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(10) = "3|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(11) = "3|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(12) = "4|||FontName|ForeColor|FontMenu|FontSize|Bold|Italic|UnderLine|StrikeThrough|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|OrderedList|UnOrderedList|Image|Flash|Media|File|Emot|ParagraphMenu|||工具栏1|||1"
aToolbar(13) = "5|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(14) = "5|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(15) = "6|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(16) = "6|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(17) = "6|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(18) = "7|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(19) = "7|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(20) = "7|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(21) = "8|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(22) = "8|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(23) = "8|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(24) = "9|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(25) = "9|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(26) = "9|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Maximize|About|||高级工具栏|||3"
aToolbar(27) = "10|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|TBSep|EditMenu|FontMenu|ParagraphMenu|ComponentMenu|ObjectMenu|ToolMenu|FormMenu|TableMenu|FileMenu|Maximize|||mini工具栏|||1"
aToolbar(28) = "11|||TBHandle|FormatBlock|FontName|FontSize|ZoomSelect|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||格式工具栏|||1"
aToolbar(29) = "11|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|TBSep|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BgColor|BackColor|BackImage|TBSep|absolutePosition|zIndexForward|zIndexBackward|||常用工具栏|||2"
aToolbar(30) = "11|||TBHandle|Image|Flash|Media|File|TBSep|TableMenu|FormMenu|ShowBorders|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|Symbol|Emot|Excel|NowDate|NowTime|TBSep|Quote|TBSep|Save|About|||高级工具栏|||3"
%>