INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(15,'中原高速公路股份有限公司 ','中原高速公路股份有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(16,'高速公路收费还贷中心总部','高速公路收费还贷中心总部',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(17,'还贷中心少新管理处','还贷中心少新管理处',16,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(13,'河南省交通运输厅高速公路管理局','河南省交通运输厅高速公路管理局',0,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(14,'河南省高速公路发展有限公司','河南省高速公路发展有限公司
',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(18,'还贷中心濮鹤管理处','还贷中心濮鹤管理处',16,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(19,'还贷中心宛坪管理处','还贷中心宛坪管理处',16,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(24,'少洛运营管理中心','少洛运营管理中心',17,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(21,'还贷中心新郑管理处','还贷中心新郑管理处',16,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(22,'高发公司潢川分公司','高发公司潢川分公司',14,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(23,'中原股份郑州分公司','中原股份郑州分公司',15,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(25,'济洛运营管理中心','济洛运营管理中心',17,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(26,'长济运营管理中心','长济运营管理中心',17,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(27,'安新运营管理中心','安新运营管理中心',18,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(28,'安南运营管理中心','安南运营管理中心',18,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(29,'濮阳至鹤壁管理处','濮阳至鹤壁管理处',18,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(30,'宛坪运营管理中心','宛坪运营管理中心',19,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(31,'省交通厅新乡至郑州管理处','省交通厅新乡至郑州管理处',21,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(32,'大广高速息县路政大队','大广高速息县路政大队',22,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(33,'郑石高速郑州路政大队','郑石高速郑州路政大队',23,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(34,'郑石高速长葛路政大队','郑石高速长葛路政大队',23,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(35,'少洛高速路政一大队','少洛高速路政一大队',24,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(36,'少洛高速路政二大队','少洛高速路政二大队',24,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(37,'济洛高速路政一大队','济洛高速路政一大队',25,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(38,'济洛高速路政二大队','济洛高速路政二大队',25,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(39,'长济高速新济路政一大队','长济高速新济路政一大队',26,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(40,'长济高速新济路政二大队','长济高速新济路政二大队',26,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(41,'长济高速新济路政三大队','长济高速新济路政三大队',26,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(47,'大广高速濮阳路政大队','大广高速濮阳路政大队',29,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(43,'大广高速安新路政一大队','大广高速安新路政一大队',27,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(44,'大广高速安新路政二大队','大广高速安新路政二大队',27,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(45,'南林高速安南路政大队','南林高速安南路政大队',28,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(46,'范辉高速濮鹤路政大队','范辉高速濮鹤路政大队',29,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(48,'沪陕高速宛坪路政一大队','沪陕高速宛坪路政一大队',30,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(49,'沪陕高速宛坪路政二大队','沪陕高速宛坪路政二大队',30,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(50,'沪陕高速宛坪路政三大队','沪陕高速宛坪路政三大队',30,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(51,'京港澳高速原阳路政大队','京港澳高速原阳路政大队',31,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(52,'京港澳高速圃田路政大队','京港澳高速圃田路政大队',31,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(53,'郑州西南绕城高速路政大队','郑州西南绕城高速路政大队',31,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(54,'许平南高速公路有限责任公司','许平南高速公路有限责任公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(55,'漯周界高速公路有限公司','漯周界高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(56,'漯平高速公路发展有限公司','漯平高速公路发展有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(57,'平顶山平临高速公路公司','平顶山平临高速公路公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(58,'开封阿深黄河大桥有限公司','开封阿深黄河大桥有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(59,'平正高速公路发展有限公司','平正高速公路发展有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(60,'光彩信阳高速公路有限公司','光彩信阳高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(61,'河南豫南高速投资有限公司','河南豫南高速投资有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(62,'洛阳市公路局洛界高速管理处','洛阳市公路局洛界高速管理处',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(63,'南阳市高速公路有限公司','南阳市高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(64,'平顶山太澳高速公路有限公司','平顶山太澳高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(65,'开封路达开发管理有限责任公司','开封路达开发管理有限责任公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(66,'开封市兰尉高速公路发展有限公司','开封市兰尉高速公路发展有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(67,'瑞贝卡尉许高速公路发展公司','瑞贝卡尉许高速公路发展公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(68,'河南鼎祥高速公路有限公司','河南鼎祥高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(69,'焦作新时代高速公路有限公司','焦作新时代高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(70,'郑州路桥集团建设发展分公司','郑州路桥集团建设发展分公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(71,'光彩新乡高速公路有限公司','光彩新乡高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(72,'山东高速集团河南许亳有限公司','山东高速集团河南许亳有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(73,'山东高速集团河南许禹有限公司','山东高速集团河南许禹有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(74,'平顶山市叶舞高速公路有限公司','平顶山市叶舞高速公路有限公司',13,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(75,'兰南高速许昌路政大队','兰南高速许昌路政大队',54,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(76,'兰南高速叶县路政大队','兰南高速叶县路政大队',54,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(77,'兰南高速方城路政大队','兰南高速方城路政大队',54,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(78,'南洛高速漯周界路政大队','南洛高速漯周界路政大队',55,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(79,'南洛高速漯平路政大队','南洛高速漯平路政大队',56,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(80,'南洛高速平临路政大队','南洛高速平临路政大队',57,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(81,'大广高速开封黄河大桥路政大队','大广高速开封黄河大桥路政大队',58,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(82,'大广高速平正路政大队','大广高速平正路政大队',59,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(83,'大广高速光山路政大队','大广高速光山路政大队',60,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(84,'大广高速新县路政大队','大广高速新县路政大队',61,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(85,'二广高速洛界路政大队','二广高速洛界路政大队',62,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(86,'二广高速南邓路政大队','二广高速南邓路政大队',63,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(87,'二广高速汝州路政大队','二广高速汝州路政大队',64,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(88,'兰南高速王兰路政大队','兰南高速王兰路政大队',65,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(89,'兰南高速兰尉路政大队','兰南高速兰尉路政大队',66,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(90,'兰南高速尉许路政大队','兰南高速尉许路政大队',67,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(91,'南林高速安林路政大队','南林高速安林路政大队',68,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(92,'郑焦晋高速公路路政大队','郑焦晋高速公路路政大队',69,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(93,'郑少高速路政大队','郑少高速路政大队',70,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(94,'长济高速新长路政大队','长济高速新长路政大队',71,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(95,'永登高速许亳路政大队','永登高速许亳路政大队',72,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(96,'永登高速许禹路政大队','永登高速许禹路政大队',73,0)
/
INSERT INTO BASE_DEPT
("DEPTID","DPTNAME","DPTINFO","PARENTID","STATUS")
VALUES
(97,'焦桐高速叶舞路产管理大队','焦桐高速叶舞路产管理大队',74,0)
/

