SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_ROLE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_ROLE](
	[ROLEID] [int] IDENTITY(1,1) NOT NULL,
	[ROLENAME] [varchar](50) NULL,
	[ROLEIDPARENT] [int] NULL CONSTRAINT [DF_BASE_ROLE_ROLEIDPARENT]  DEFAULT ((0)),
	[SORT] [int] NULL CONSTRAINT [DF_BASE_ROLE_SORT]  DEFAULT ((1)),
	[SUMMARY] [varchar](50) NULL,
	[ENABLE] [int] NULL CONSTRAINT [DF_BASE_ROLE_ENABLE]  DEFAULT ((0)),
 CONSTRAINT [PK_BASE_ROLE] PRIMARY KEY CLUSTERED 
(
	[ROLEID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'?????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_ROLE'

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_TOPIC]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_TOPIC](
	[TOPICID] [int] IDENTITY(1,1) NOT NULL,
	[TOPICNAME] [varchar](50) NULL,
	[SUMMARY] [varchar](50) NULL,
	[SCORE] [int] NULL CONSTRAINT [DF_BASE_TOPIC_SCORE]  DEFAULT ((0)),
	[TOPICIDPARENT] [int] NULL CONSTRAINT [DF_BASE_TOPIC_TOPICIDPARENT]  DEFAULT ((0)),
	[ENABLE] [int] NULL CONSTRAINT [DF_BASE_TOPIC_ENABLE]  DEFAULT ((0)),
	[SORT] [int] NULL CONSTRAINT [DF_BASE_TOPIC_SORT]  DEFAULT ((1)),
 CONSTRAINT [PK_BASE_TOPIC] PRIMARY KEY CLUSTERED 
(
	[TOPICID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'?????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_TOPIC'

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_USER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_USER](
	[USERID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](18) NULL,
	[USERPWD] [varchar](32) NULL CONSTRAINT [DF_BASE_USER_USERPWD]  DEFAULT ('21232F297A57A5A743894A0E4A801FC3'),
	[ROLEID] [varchar](50) NULL CONSTRAINT [DF_BASE_USER_ROLEID]  DEFAULT ((0)),
 CONSTRAINT [PK_BASE_USER] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'?????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_USER'

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_WARNING]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_WARNING](
	[WARNINGID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[DETAIL] [varchar](50) NULL,
	[GENERATEDATE] [datetime] NULL CONSTRAINT [DF_BASE_WARNING_GENERATEDATE]  DEFAULT (getdate()),
	[ARTICLE] [int] NULL CONSTRAINT [DF_BASE_WARNING_ARTICLE]  DEFAULT ((0)),
	[ENABLE] [int] NULL CONSTRAINT [DF_BASE_WARNING_ENABLE]  DEFAULT ((0)),
	[SNAPSHOT] [varchar](50) NULL,
	[ISREAD] [int] NULL CONSTRAINT [DF_BASE_WARNING_ISREAD]  DEFAULT ((0)),
	[SORT] [int] NULL CONSTRAINT [DF_BASE_WARNING_SORT]  DEFAULT ((0)),
 CONSTRAINT [PK_BASE_WARNING] PRIMARY KEY CLUSTERED 
(
	[WARNINGID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'?????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_WARNING'

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_ARTICLE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_ARTICLE](
	[ARTICLEID] [int] IDENTITY(1,1) NOT NULL,
	[TOPICID] [varchar](500) NULL CONSTRAINT [DF_BASE_ARTICLE_TOPICID]  DEFAULT ((0)),
	[TITLE] [varchar](200) NULL,
	[PUBLISHDATE] [datetime] NULL CONSTRAINT [DF_BASE_ARTICLE_PUBLISHDATE]  DEFAULT (getdate()),
	[SOURCE] [varchar](50) NULL,
	[AUTHOR] [varchar](50) NULL,
	[CLICK] [int] NULL CONSTRAINT [DF_BASE_ARTICLE_CLICK]  DEFAULT ((0)),
	[COMMENT] [int] NULL CONSTRAINT [DF_BASE_ARTICLE_COMMENT]  DEFAULT ((0)),
	[DETAIL] [varchar](8000) NULL,
	[REFERER] [varchar](1024) NULL,
	[EXTRACTIONDATE] [datetime] NULL CONSTRAINT [DF_BASE_ARTICLE_EXTRACTIONDATE]  DEFAULT (getdate()),
	[SCORE] [float] NULL CONSTRAINT [DF_BASE_ARTICLE_SCORE]  DEFAULT ((0)),
 CONSTRAINT [PK_BASE_ARTICLE] PRIMARY KEY CLUSTERED 
(
	[ARTICLEID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'?????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_ARTICLE'

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BASE_WORD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BASE_WORD](
	[WORDID] [int] IDENTITY(1,1) NOT NULL,
	[WORDNAME] [varchar](50) NULL,
	[SCORE] [float] NULL CONSTRAINT [DF_BASE_WORD_SCORE]  DEFAULT ((0)),
	[WORDIDPARENT] [int] NULL CONSTRAINT [DF_BASE_WORD_WORDIDPARENT]  DEFAULT ((0)),
	[ENABLE] [int] NULL CONSTRAINT [DF_BASE_WORD_ENABLE]  DEFAULT ((0)),
	[TOPICID] [varchar](500) NULL CONSTRAINT [DF_BASE_WORD_TOPICID]  DEFAULT ((0)),
 CONSTRAINT [PK_BASE_WORD] PRIMARY KEY CLUSTERED 
(
	[WORDID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'??????' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'BASE_WORD'

